### ISSUE TITLE
'target-counter' browser support

### ISSUE THREAD

**Issue by debeetle** [thomaspark/pubcss#49]
Thanks for this project! I've been benefit a lot for creating my own article css. 

However, I got stuck at the `target-counter` css function. After digging the internet, it seems like most browser has not implemented it yet. Am I missing something? How can I get the `<a href="#example-figure" class="figure"></a>` work properly? In other words, does it only work with `prince`? 

I also checked the resource of the [interactive web paper](https://thomaspark.co/projects/pubcss/demo/acm-sig-sample-web-theme.html) mentioned in the [sample output blog](http://thomaspark.me/2015/01/pubcss-formatting-academic-publications-in-html-css/). Found that it manually set the content in the `<a>` tag like `cite href="#tablefreq" class="table">1</cite>` to show the counter, which uses `cite` here. And the `cite` css is:
```css
cite.table {
  content: target-counter(attr(href, url), table);
}
cite.table:before {
  content: "Table ";
}
cite.table:after {
  content: "";
}
```

Looking forward to the response.
